### ISSUE TITLE
Some errors need help

### ISSUE THREAD

**Issue by sunshinewhy** [orestis-z/facial-beauty-predictor#1]
When I run generate_features_async.py file in my windows computer, the terminal shows the error that:
Traceback (most recent call last):
  File "scripts/generate_features_async.py", line 76, in <module>
    main(args)
  File "scripts/generate_features_async.py", line 16, in main
    db = db_dict["all"]
KeyError: 'all'
PS D:\PycharmProjects\facial-beauty-predictor-master>
Could you tell me how to solve it? Thanks a lot!

**Comment by orestis-z** [comment]
You need to make sure you've converted the datasets and set the correct `--db`
