### ISSUE TITLE
Errors Setting up

### ISSUE THREAD

**Issue by claytonsulby** [orestis-z/facial-beauty-predictor#2]
Hello!

Setting this up on my MacBook Pro. Brew installed Python 3.7 and aliased as python3.7 in the terminal. I couldn't determine which dataset was the tinder dataset so the conversion error may be my own mistake. How would I resolve the error for: 

Traceback (most recent call last):
  File "scripts/generate_features_async.py", line 11, in <module>
    from facial_beauty_predictor.worker import worker_mtcnn_async, worker_mtcnn_facenet_async, worker_mtcnn_facenet_2_async
ModuleNotFoundError: No module named 'facial_beauty_predictor'

Error converting tinder
![image](https://user-images.githubusercontent.com/48489392/183251044-ea075fdf-c4fc-4220-b0b3-8aa092b567b9.png)

Error running generate
![image](https://user-images.githubusercontent.com/48489392/183251000-186986f6-e04b-4891-9bd0-e1b3f9456d63.png)

**Comment by orestis-z** [comment]
- You need to add `facial_beauty_predictor` to your python path
- You need to set the correct `--db-dir`
